server:
  port: 8080

spring:
  application:
    name: appointment_service

  datasource:
    url: jdbc:mysql://localhost:3306/doctor_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: "20001120rsa"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.hospital.appointment_service.client: DEBUG
