server:
  port: 8080   # choose a free port

spring:
  application:
    name: feedback-service

  datasource:
    url: jdbc:mysql://localhost:3306/feedback_db
    username: root
    password: Lenovo1234#

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


jwt:
  secret: nXGv6WQmZc7y1q3lV2t9Rk8pHs4aYd0uJfL5sB2cT8E=