server:
  port: 8085   # choose a different free port

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: Lenovo1234#
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  security:
    user:
      name: sahan
      password: lenora

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: nXGv6WQmZc7y1q3lV2t9Rk8pHs4aYd0uJfL5sB2cT8E=

