spring:
  application:
    name: doctor-service

  datasource:
    url: jdbc:mysql://localhost:3306/doctor_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Yash20019821
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # automatically creates/updates tables
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # Removed MySQL8Dialect because Hibernate 7 auto-detects MySQL version

server:
  port: 8082